### ISSUE TITLE
Fan keeps cycling back to full blast RPMs or 100% duty cycle

### ISSUE THREAD

**Issue by HiepTLe** [chenxiaolong/ipmi-fan-control#43] opened 2022-07-14 18:57 UTC
I'm not sure what's causing this but every couple minutes or so my fans go full blast before the script kicks in.
     
`      [[zones]]

        ipmi_zones = [0]
        interval = 5
        sources = [
            { type = "ipmi", sensor = "CPU Temp" },
            { type = "file", path = "/sys/class/thermal/thermal_zone1/temp" },
        ]
        steps = [
            { temp = 30, dcycle = 10 },
            { temp = 35, dcycle = 15 },
            { temp = 40, dcycle = 20 },
            { temp = 50, dcycle = 30 },
            { temp = 60, dcycle = 50 },
        ]
        [[zones]]
        ipmi_zones = [1]
        interval = 5
        sources = [
            { type = "ipmi", sensor = "PCH Temp" },
            { type = "file", path = "/sys/class/thermal/thermal_zone1/temp" },
        ]
        steps = [
            { temp = 30, dcycle = 10 },
            { temp = 35, dcycle = 15 },
            { temp = 40, dcycle = 20 },
            { temp = 50, dcycle = 30 },
            { temp = 60, dcycle = 50 },
        ]
        [sessions]`

**Comment by chenxiaolong** [comment] 2022-07-14 19:10
Do any errors show up in the system logs? Eg. `journalctl -u ipmi-fan-control --since '1 hour ago'`

One way I think this could happen is if ipmi-fan-control is crashing and restarting. When it starts up initially, the fans are set to full blast.

**Comment by HiepTLe** [comment] 2022-07-14 19:54
No errors in sys logs.
```
journalctl -u ipmi-fan-control --since '1 hour ago'
-- Logs begin at Thu 2022-07-14 12:17:15 CDT, end at Thu 2022-07-14 14:53:10 CDT. --
-- No entries --
```

**Comment by chenxiaolong** [comment] 2022-07-14 21:11
Interesting. How are you running ipmi-fan-control? Are you using the systemd service or just running the command manually?

**Comment by HiepTLe** [comment] 2022-07-14 21:26
I was running a bash script that ran 'ipmi-fan-control/target/release/ipmi-fan-control --config ipmi-fan-control/config.toml'
and the bash script was the fancontrols.service
Then I recently tried deleting the bash script and running the command directly through the service instead of calling the bash script. Both worked mostly the same.

Running the debugger, I got this 
```
[2022-07-14T21:11:54Z INFO  ipmi_fan_control] [default] Restoring fan mode to: Standard
[2022-07-14T21:11:54Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x45 1 0'
[2022-07-14T21:11:54Z ERROR ipmi_fan_control] IPMI error: Failed to interact with ipmitool: Timeout Error: Expected Regex: "^\s+\(\+/-\s+[\d\.]+\)\s+" but got "`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
    `\r``\n`
    ipmitool> " (after waiting 2000 ms)
```

When I tried to run the error command manually I get this:
```
[root]# ipmitool -v raw 0x30 0x45 1 0
Running Get PICMG Properties my_addr 0x20, transit 0, target 0
Error response 0xc1 from Get PICMG Properities
Running Get VSO Capabilities my_addr 0x20, transit 0, target 0
Invalid completion code received: Invalid command
Discovered IPMB address 0x0
RAW REQ (channel=0x0 netfn=0x30 lun=0x0 cmd=0x45 data_len=2)
RAW REQUEST (2 bytes)
 01 00
RAW RSP (0 bytes)

```

**Comment by HiepTLe** [comment] 2022-07-14 21:29
It gives the same error when I had it set to "full mode", I only had it on standard for testing.

**Comment by chenxiaolong** [comment] 2022-07-14 21:59
```
[2022-07-14T21:11:54Z ERROR ipmi_fan_control] IPMI error: Failed to interact with ipmitool: Timeout Error: Expected Regex: "^\s+\(\+/-\s+[\d\.]+\)\s+" but got "`\r``\n`
```
Interesting. The error is happening when parsing the output of `ipmitool sdr get <sensor>`. I wonder if ipmitool is reporting the temperature readings in a different format with your motherboard. On my server, ipmitool reports temperatures in this format:
```
Sensor Reading        : 47 (+/- 0) degrees C
```

Can you post the full output of this command?
```
ipmitool sdr get 'CPU Temp' 'PCH Temp'
```

**Comment by HiepTLe** [comment] 2022-07-15 15:24
I get this: 
```
[root]# ipmitool sdr get 'CPU Temp' 'PCH Temp'
Sensor ID              : CPU Temp (0x1)
 Entity ID             : 3.1 (Processor)
 Sensor Type (Threshold)  : Temperature (0x01)
 Sensor Reading        : 24 (+/- 0) degrees C
 Status                : ok
 Nominal Reading       : 20.000
 Normal Minimum        : 11.000
 Normal Maximum        : 80.000
 Upper non-recoverable : 100.000
 Upper critical        : 100.000
 Upper non-critical    : 95.000
 Lower non-recoverable : 5.000
 Lower critical        : 5.000
 Lower non-critical    : 10.000
 Positive Hysteresis   : 2.000
 Negative Hysteresis   : 2.000
 Minimum sensor range  : Unspecified
 Maximum sensor range  : Unspecified
 Event Message Control : Per-threshold
 Readable Thresholds   : lnr lcr lnc unc ucr unr 
 Settable Thresholds   : lnr lcr lnc unc ucr unr 
 Assertion Events      : 
 Assertions Enabled    : 

Sensor ID              : PCH Temp (0xa)
 Entity ID             : 7.1 (System Board)
 Sensor Type (Threshold)  : Temperature (0x01)
 Sensor Reading        : 25 (+/- 0) degrees C
 Status                : ok
 Nominal Reading       : 20.000
 Normal Minimum        : 11.000
 Normal Maximum        : 84.000
 Upper non-recoverable : 105.000
 Upper critical        : 90.000
 Upper non-critical    : 85.000
 Lower non-recoverable : 5.000
 Lower critical        : 5.000
 Lower non-critical    : 10.000
 Positive Hysteresis   : 2.000
 Negative Hysteresis   : 2.000
 Minimum sensor range  : Unspecified
 Maximum sensor range  : Unspecified
 Event Message Control : Per-threshold
 Readable Thresholds   : lnr lcr lnc unc ucr unr 
 Settable Thresholds   : lnr lcr lnc unc ucr unr 
 Threshold Read Mask   : ucr unr 
 Assertion Events      : 
 Assertions Enabled    : ucr+ unr+ 
 Deassertions Enabled  : ucr+ unr+ 
```

**Comment by chenxiaolong** [comment] 2022-07-22 01:05
Hmm, so the format is the same as what I have on my server. I wonder if it might be returning an unexpected value when querying sensors immediately after switching the fan mode. I'll see if I can update ipmi-fan-control this weekend to add a retry loop for querying the sensors.

**Comment by stigger** [comment] 2022-09-13 00:49
All of a sudden I started having the same issue: it happened suddenly, no software updates, no restarts, nothing. Symptoms are very similar: it starts, works for 30 seconds, then errors and exits. Tried resetting the BMC and reloading kernel `ipmi_*` modules. Not sure how to troubleshoot it further.

```
[2022-09-13T00:41:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x45 0'
[2022-09-13T00:41:12Z INFO  ipmi_fan_control] [default] Original fan mode: Full
[2022-09-13T00:41:12Z INFO  ipmi_fan_control] [default] Setting fan mode to: Full
[2022-09-13T00:41:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x45 1 1'
[2022-09-13T00:41:12Z INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [0]
[2022-09-13T00:41:12Z INFO  ipmi_fan_control] [default] Starting loop for IPMI zones [1]
[2022-09-13T00:41:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:13Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=38C, dcycle_cur=100%, dcycle_new=21%
[2022-09-13T00:41:13Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:13Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 1'
[2022-09-13T00:41:13Z INFO  ipmi_fan_control] [default] Zone 1: zone_temp=42C, dcycle_cur=100%, dcycle_new=50%
[2022-09-13T00:41:13Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 1 50'
[2022-09-13T00:41:18Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:18Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:18Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=35C, dcycle_cur=100%, dcycle_new=21%
[2022-09-13T00:41:18Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:23Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=35C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T00:41:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:28Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:28Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:29Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=35C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T00:41:29Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:33Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 1'
[2022-09-13T00:41:33Z INFO  ipmi_fan_control] [default] Zone 1: zone_temp=42C, dcycle_cur=100%, dcycle_new=50%
[2022-09-13T00:41:33Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 1 50'
[2022-09-13T00:41:34Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:34Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:34Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=37C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T00:41:34Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:39Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:39Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:39Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=35C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T00:41:39Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:44Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:44Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 0 0'
[2022-09-13T00:41:44Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=34C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T00:41:44Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 21'
[2022-09-13T00:41:50Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'sdr get 'CPU Temp''
[2022-09-13T00:41:52Z INFO  ipmi_fan_control] [default] Setting zone 0 duty cycle to 100%
[2022-09-13T00:41:52Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 0 100'
[2022-09-13T00:41:52Z INFO  ipmi_fan_control] [default] Setting zone 1 duty cycle to 100%
[2022-09-13T00:41:52Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x70 0x66 1 1 100'
[2022-09-13T00:41:52Z INFO  ipmi_fan_control] [default] Restoring fan mode to: Full
[2022-09-13T00:41:52Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: 'raw 0x30 0x45 1 1'
[2022-09-13T00:41:52Z ERROR ipmi_fan_control] IPMI error: Failed to interact with ipmitool: Timeout Error: Expected Regex: "^\s+\(\+/-\s+[\d\.]+\)\s+" but got "`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
    `\r``\n`
    ipmitool> " (after waiting 2000 ms)
ipmi-fan-control.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by chenxiaolong** [comment] 2022-09-13 20:45
I created #44 with several improvements in parsing `ipmitool shell`'s output and also added support for retries (2 retries by default with 500ms delay). I'll release version 0.3.7 with those changes today.

It doesn't fix the underlying issue, but should (hopefully) work around it. If you wouldn't mind providing debug logs again after the version 0.3.7 update, I'd appreciate it. I believe the issue is that ipmitool is sometimes returning sensor readings without units (eg. `degrees C`), but the new debug logs should help confirm if that's the case. (`retries = 0` can be set in the config for the old behavior of failing on the first error in case that helps with grabbing logs of the error.)

**Comment by stigger** [comment] 2022-09-13 23:44
Thanks a lot! Looks like my sensor occasionally doesn't have a reading, and ipmi-fan-control cannot recover after that:

```
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 1/5)
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "38"
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading accuracy: " (+/- 0) "
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading units: "degrees C"
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 0 0"
[2022-09-13T23:35:55Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=38C, dcycle_cur=21%, dcycle_new=21%
[2022-09-13T23:35:55Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 1 0 21"
[2022-09-13T23:36:00Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 1/5)
[2022-09-13T23:36:00Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:36:00Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "20.000"
[2022-09-13T23:36:03Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 2/5)
[2022-09-13T23:36:03Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:36:05Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 3/5)
[2022-09-13T23:36:05Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:36:08Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 4/5)
[2022-09-13T23:36:08Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:36:10Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 5/5)
[2022-09-13T23:36:10Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-13T23:36:12Z INFO  ipmi_fan_control] [default] Setting zone 0 duty cycle to 100%
[2022-09-13T23:36:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 1 0 100"
[2022-09-13T23:36:12Z INFO  ipmi_fan_control] [default] Setting zone 1 duty cycle to 100%
[2022-09-13T23:36:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 1 1 100"
[2022-09-13T23:36:12Z INFO  ipmi_fan_control] [default] Restoring fan mode to: Full
[2022-09-13T23:36:12Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x45 1 1"
[2022-09-13T23:36:12Z ERROR ipmi_fan_control] Failed all 5 attempt(s); last attempt error: IPMI error: Failed to parse sensor output: ID line not found: Timeout Error: Expected Regex: "(^|\n)(Sensor ID\s+:\s+|Unable to find sensor id ')" but got "`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
    `\r``\n`
    ipmitool> Sensor ID              : CPU Temp (0x1)`\r``\n`
     Entity ID             : 3.1 (Processor)`\r``\n`
     Sensor Type (Threshold)  : Temperature (0x01)`\r``\n`
     Sensor Reading        : 38 (+/- 0) degrees C`\r``\n`
     Status                : ok`\r``\n`
     Nominal Reading       : 20.000`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Assertion Events      : `\r``\n`
     Assertions Enabled    : `\r``\n`
    `\r``\n`
    ipmitool> Sensor ID              : CPU Temp (0x1)`\r``\n`
     Entity ID             : 3.1 (Processor)`\r``\n`
     Sensor Type (Threshold)  : Temperature (0x01)`\r``\n`
     Sensor Reading        : 37 (+/- 0) degrees C`\r``\n`
     Status                : ok`\r``\n`
     Nominal Reading       : 20.000`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Assertion Events      : `\r``\n`
     Assertions Enabled    : `\r``\n`
    `\r``\n`
    ipmitool> Sensor ID              : CPU Temp (0x1)`\r``\n`
     Entity ID             : 3.1 (Processor)`\r``\n`
     Sensor Type (Threshold)  : Temperature (0x01)`\r``\n`
     Sensor Reading        : 38 (+/- 0) degrees C`\r``\n`
     Status                : ok`\r``\n`
     Nominal Reading       : 20.000`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Assertion Events      : `\r``\n`
     Assertions Enabled    : `\r``\n`
    `\r``\n`
    ipmitool> Sensor ID              : CPU Temp (0x1)`\r``\n`
     Entity ID             : 3.1 (Processor)`\r``\n`
     Sensor Type (Threshold)  : Temperature (0x01)`\r``\n`
     Sensor Reading        : No Reading`\r``\n`
     Status                : Not Available`\r``\n`
     Nominal Reading       : 20.000`\r``\n`
     Normal Minimum        : 11.000`\r``\n`
     Normal Maximum        : 80.000`\r``\n`
     Upper non-recoverable : 100.000`\r``\n`
     Upper critical        : 100.000`\r``\n`
     Upper non-critical    : 95.000`\r``\n`
     Lower non-recoverable : 5.000`\r``\n`
     Lower critical        : 5.000`\r``\n`
     Lower non-critical    : 10.000`\r``\n`
     Positive Hysteresis   : 2.000`\r``\n`
     Negative Hysteresis   : 2.000`\r``\n`
     Minimum sensor range  : Unspecified`\r``\n`
     Maximum sensor range  : Unspecified`\r``\n`
     Event Message Control : Per-threshold`\r``\n`
     Readable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
     Settable Thresholds   : lnr lcr lnc unc ucr unr `\r``\n`
    `\r``\n`
    ipmitool> " (after waiting 2000 ms)
```

By the way, the actual delay between attempts doesn't seem to correspond to the configured `retry_delay_ms`.

**Comment by chenxiaolong** [comment] 2022-09-14 01:31
Thanks for the logs! That's interesting, I haven't seen the BMC sometimes not report a value before.

I think I know why the retry is broken. When it fails, it's not discarding the output and looking for the `ipmitool> ` prompt, so the next attempt starts off in a bad state. I'll get that fixed tomorrow. I believe this is also why the delay between attempts is off. When the state of the ipmitool output gets desynced, it times out for 2 seconds and then waits for `retry_delay_ms` after that.

At some point in the near future, I'll rewrite ipmi-fan-control to use an actual IPMI library. Parsing the human-readable output from `ipmitool shell` is too fragile.

**Comment by chenxiaolong** [comment] 2022-09-14 16:47
The output desync on retries should be fixed in version 0.3.9.

**Comment by stigger** [comment] 2022-09-14 17:56
Works perfectly now, thanks a lot!
```
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 1/5)
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "36"
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading tolerance: " (+/- 0) "
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading units: "degrees C"
[2022-09-14T17:51:15Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 0 0"
[2022-09-14T17:51:16Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=36C, dcycle_cur=21%, dcycle_new=21%
[2022-09-14T17:51:16Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 1 0 21"
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 1/5)
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "Not Available"
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 2/5)
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-14T17:51:21Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "Not Available"
[2022-09-14T17:51:22Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 3/5)
[2022-09-14T17:51:22Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-14T17:51:22Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "Not Available"
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control] Querying sources for zones [0] (attempt 4/5)
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "sdr get 'CPU Temp'"
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading value: "36"
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading tolerance: " (+/- 0) "
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Sensor "CPU Temp" reading units: "degrees C"
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 0 0"
[2022-09-14T17:51:23Z INFO  ipmi_fan_control] [default] Zone 0: zone_temp=36C, dcycle_cur=21%, dcycle_new=21%
[2022-09-14T17:51:23Z DEBUG ipmi_fan_control::ipmi] Running IPMI command: "raw 0x30 0x70 0x66 1 0 21"
```
The only minor issue left is the seemingly unnecessary execution of ipmi commands after restoration: the value hasn't changed, we're re-setting exactly the same numbers.

**Comment by chenxiaolong** [comment] 2022-09-14 18:22
> The only minor issue left is the seemingly unnecessary execution of ipmi commands after restoration: the value hasn't changed, we're re-setting exactly the same numbers.

That's a great idea and super easy to implement. I'll fix that!

**Closed as completed** 2022-09-14 18:37 UTC
